<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\..\common.props"/>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>AISmart</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AISmart.Application.Contracts\AISmart.Application.Contracts.csproj"/>
        <ProjectReference Include="..\AISmart.Application.Grains\AISmart.Application.Grains.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoGen"/>
        <PackageReference Include="AutoGen.Core"/>
        <PackageReference Include="Microsoft.Orleans.EventSourcing"/>
        <PackageReference Include="Microsoft.SemanticKernel"/>
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.Amazon"/>
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google"/>
        <PackageReference Include="Microsoft.SemanticKernel.Core"/>
        <PackageReference Include="Volo.Abp.AutoMapper"/>
        <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureAIInference"/>
        <PackageReference Include="Microsoft.Extensions.AI.Abstractions"/>
    </ItemGroup>

</Project>
